PongR/Controllers/JsTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PongR.Controllers
{
    public class JsTestController : Controller
    {
        //
        // GET: /JsTest/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PongR()
        {
            return View();
        }
    }
}

PongR/Views/JsTest/Index.cshtml
<h2>QUnit Test page</h2>

<ul>
@{
    var controller = ViewContext.Controller.GetType();
    var methods = controller.GetMethods()
        .Where(m => m.ReturnType.ToString() == "System.Web.Mvc.ActionResult");

    foreach(var method in methods)
    {
        <li>@Html.ActionLink(@method.Name, @method.Name, "JsTest")</li>
    }
}
</ul>

PongR/Views/JsTest/PongR.cshtml
@{
    ViewBag.Title = "PongR.js Tests";
}

@section Javascript{
    <script src="@Url.Content("~/Js/PongR.js")"></script>
    <script src="@Url.Content("~/Js/test/PongR_test.js")"></script>
}

@Html.Partial("_QUnit")

PongR/Views/JsTest/_JsTestLayout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" href="@Url.Content("~/Content/qunit.css")" />
        <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.signalR-0.5.3.min.js")" type="text/javascript"></script>
        <script type="text/javascript" src="@Url.Content("~/Js/RequestAnimationFrameShim.js")"></script>
        <script type="text/javascript" src="@Url.Content("/signalr/hubs")"></script>         
        <script src="@Url.Content("~/Scripts/knockout-2.1.0.js")" type="text/javascript"></script>    
        <script src="@Url.Content("~/Scripts/keyboard.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/qunit.js")"></script>        
        @RenderSection("Javascript", false)
    </head>
    <body>
        @RenderBody()
    </body>
</html>

PongR/Views/JsTest/_QUnit.cshtml
<h2>@ViewBag.Title</h2>

<h1 id="qunit-header">QUnit example</h1>
<h2 id="qunit-banner"></h2>
<h2 id="qunit-userAgent"></h2>
<ol id="qunit-tests">
</ol>

@Html.ActionLink("Back to Tests", "Index", "JsTest")